# Generated by Django 4.0.2 on 2022-02-22 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('producto', models.CharField(blank=True, max_length=500, null=True)),
                ('resultado', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('letra', models.CharField(blank=True, max_length=20)),
                ('mission', models.TextField(blank=True)),
                ('function', models.TextField(blank=True)),
                ('decreto', models.CharField(blank=True, max_length=50)),
                ('marco_legal', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('procesos_participativos', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.estructura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('peso', models.FloatField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('Inciso', models.CharField(max_length=20)),
                ('cantidad', models.FloatField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=500)),
                ('descripcion_alternativa', models.CharField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField()),
                ('tiene_indicador', models.BooleanField()),
                ('prefer', models.FloatField(default=1)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('Objetivos_Precedentes', models.ManyToManyField(blank=True, to='objetivos.Objetivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrioridadAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipofuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('func', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tema_Estrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('situacion_actual', models.TextField(blank=True, max_length=2000, null=True)),
                ('situacion_deseada', models.TextField(blank=True, max_length=2000, null=True)),
                ('id_estructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.estructura')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivos.objetivo')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetivos.estructura')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='politica_publica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.politica_publica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parama', models.FloatField(blank=True, null=True)),
                ('paramb', models.FloatField(blank=True, null=True)),
                ('paramc', models.FloatField(blank=True, null=True)),
                ('paramd', models.FloatField(blank=True, null=True)),
                ('vigencia', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_creator', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.indicador')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.ods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='objetivo',
            name='id_Tema_Estrategico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.tema_estrategico'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='id_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.actividad'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='id_estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.estructura'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.objetivo'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='id_Tipo_Indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.tipo_indicador'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='id_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.actividad'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='tipofuncion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.tipofuncion'),
        ),
        migrations.CreateModel(
            name='finalidad_y_funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.finalidad_y_funcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objetivos.eje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('detail', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_creator', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.indicador')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='Id_Tipo_Actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.tipo_actividad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_Estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.estructura'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_Objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.objetivo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.eje'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_finalidadyfuncion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.finalidad_y_funcion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_ods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.ods'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_politicapublica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.politica_publica'),
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('id_user', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('duracion', models.IntegerField()),
                ('avance', models.FloatField()),
                ('observacion', models.CharField(max_length=500)),
                ('id_EstadoAccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.estadoaccion')),
                ('id_PrioridadAccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.prioridadaccion')),
                ('id_TipoAccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.tipoaccion')),
            ],
        ),
    ]
