# Generated by Django 4.0.2 on 2022-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='beneficiario',
            field=models.ManyToManyField(blank=True, null=True, to='objetivos.Beneficiario'),
        ),
    ]
