# Generated by Django 4.0.2 on 2022-04-13 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0002_beneficiario_actividad_beneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='duracion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='problema',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='productos_secundarios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ref_presupuesto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='definicion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indicador',
            name='desagregaciones',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indicador',
            name='fuente',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indicador',
            name='modo_calculo',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='indicador',
            name='periodicidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='unidades_medida',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PresupuestoPorActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.FloatField()),
                ('avance_estimado', models.FloatField()),
                ('ejecicio', models.CharField(blank=True, max_length=50, null=True)),
                ('id_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivos.actividad')),
            ],
        ),
    ]
