# Generated by Django 4.0.2 on 2022-03-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0003_alter_estructura_decreto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo',
            old_name='name',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='objetivo',
            old_name='codigo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='id_Tema_Estrategico',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='tiene_indicador',
        ),
        migrations.AddField(
            model_name='objetivo',
            name='es_tema_estrategico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='situacion_actual',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='situacion_deseada',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
