# Generated by Django 4.0.2 on 2022-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0004_actividad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='beneficiario',
            field=models.ManyToManyField(blank=True, to='objetivos.Beneficiario'),
        ),
    ]
